### ISSUE TITLE
fix module loading 

### ISSUE THREAD

**Issue by tlford82** [SaintsSec/Navi#47]
python3 navi-shell.py 
Module 'bullet' not found
Traceback (most recent call last):
  File "/opt/Navi/commands/__init__.py", line 11, in load_module
    module = importlib.import_module(f".{name}", '.commands')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/Navi/commands/bullet.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Navi/navi-shell.py", line 6, in <module>
    import commands
  File "/opt/Navi/commands/__init__.py", line 35, in <module>
    mod = load_module(module)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/Navi/commands/__init__.py", line 11, in load_module
    module = importlib.import_module(f".{name}", '.commands')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Navi/commands/__init__.py", line 35, in <module>
    mod = load_module(module)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/Navi/commands/__init__.py", line 14, in load_module
    logging.basicConfig(
  File "/usr/lib/python3.11/logging/__init__.py", line 2050, in basicConfig
    h = FileHandler(filename, mode,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/Navi/logs/error.log'

**Comment by AlexKollar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ubuntu / Debian installation issues.](https://trello.com/c/z5NpWgYM/2-ubuntu-debian-installation-issues)

**Comment by AlexKollar** [comment]
Seems to have been a non-issue now.
